/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedTsxNotificationsRouteImport } from './routes/_protected.tsx/notifications'
import { Route as ProtectedTsxDashboardRouteImport } from './routes/_protected.tsx/dashboard'
import { Route as ProtectedTsxProtectedRouteImport } from './routes/_protected.tsx/_protected'
import { Route as ProtectedTsxCoursesIndexRouteImport } from './routes/_protected.tsx/courses/index'
import { Route as ProtectedTsxProfileSettingsRouteImport } from './routes/_protected.tsx/profile/settings'
import { Route as ProtectedTsxProfileUserIdRouteImport } from './routes/_protected.tsx/profile/$userId'
import { Route as ProtectedTsxCoursesCourseIdRouteImport } from './routes/_protected.tsx/courses/$courseId'
import { Route as ProtectedTsxClassroomLayoutRouteImport } from './routes/_protected.tsx/classroom/_layout'
import { Route as ProtectedTsxCheckoutCourseRouteImport } from './routes/_protected.tsx/checkout/$course'
import { Route as ProtectedTsxClassroomLayoutClassroomIdIndexRouteImport } from './routes/_protected.tsx/classroom/_layout/$classroomId/index'
import { Route as ProtectedTsxClassroomLayoutClassroomIdLecturesRouteImport } from './routes/_protected.tsx/classroom/_layout/$classroomId/lectures'
import { Route as ProtectedTsxClassroomLayoutClassroomIdChatRouteImport } from './routes/_protected.tsx/classroom/_layout/$classroomId/chat'
import { Route as ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRouteImport } from './routes/_protected.tsx/classroom/_layout/$classroomId/announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTsxNotificationsRoute =
  ProtectedTsxNotificationsRouteImport.update({
    id: '/_protected/tsx/notifications',
    path: '/tsx/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxDashboardRoute = ProtectedTsxDashboardRouteImport.update({
  id: '/_protected/tsx/dashboard',
  path: '/tsx/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTsxProtectedRoute = ProtectedTsxProtectedRouteImport.update({
  id: '/_protected/tsx/_protected',
  path: '/tsx',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTsxCoursesIndexRoute =
  ProtectedTsxCoursesIndexRouteImport.update({
    id: '/_protected/tsx/courses/',
    path: '/tsx/courses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxProfileSettingsRoute =
  ProtectedTsxProfileSettingsRouteImport.update({
    id: '/_protected/tsx/profile/settings',
    path: '/tsx/profile/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxProfileUserIdRoute =
  ProtectedTsxProfileUserIdRouteImport.update({
    id: '/_protected/tsx/profile/$userId',
    path: '/tsx/profile/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxCoursesCourseIdRoute =
  ProtectedTsxCoursesCourseIdRouteImport.update({
    id: '/_protected/tsx/courses/$courseId',
    path: '/tsx/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxClassroomLayoutRoute =
  ProtectedTsxClassroomLayoutRouteImport.update({
    id: '/_protected/tsx/classroom/_layout',
    path: '/tsx/classroom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxCheckoutCourseRoute =
  ProtectedTsxCheckoutCourseRouteImport.update({
    id: '/_protected/tsx/checkout/$course',
    path: '/tsx/checkout/$course',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTsxClassroomLayoutClassroomIdIndexRoute =
  ProtectedTsxClassroomLayoutClassroomIdIndexRouteImport.update({
    id: '/$classroomId/',
    path: '/$classroomId/',
    getParentRoute: () => ProtectedTsxClassroomLayoutRoute,
  } as any)
const ProtectedTsxClassroomLayoutClassroomIdLecturesRoute =
  ProtectedTsxClassroomLayoutClassroomIdLecturesRouteImport.update({
    id: '/$classroomId/lectures',
    path: '/$classroomId/lectures',
    getParentRoute: () => ProtectedTsxClassroomLayoutRoute,
  } as any)
const ProtectedTsxClassroomLayoutClassroomIdChatRoute =
  ProtectedTsxClassroomLayoutClassroomIdChatRouteImport.update({
    id: '/$classroomId/chat',
    path: '/$classroomId/chat',
    getParentRoute: () => ProtectedTsxClassroomLayoutRoute,
  } as any)
const ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute =
  ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRouteImport.update({
    id: '/$classroomId/announcements',
    path: '/$classroomId/announcements',
    getParentRoute: () => ProtectedTsxClassroomLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tsx': typeof ProtectedTsxProtectedRoute
  '/tsx/dashboard': typeof ProtectedTsxDashboardRoute
  '/tsx/notifications': typeof ProtectedTsxNotificationsRoute
  '/tsx/checkout/$course': typeof ProtectedTsxCheckoutCourseRoute
  '/tsx/classroom': typeof ProtectedTsxClassroomLayoutRouteWithChildren
  '/tsx/courses/$courseId': typeof ProtectedTsxCoursesCourseIdRoute
  '/tsx/profile/$userId': typeof ProtectedTsxProfileUserIdRoute
  '/tsx/profile/settings': typeof ProtectedTsxProfileSettingsRoute
  '/tsx/courses/': typeof ProtectedTsxCoursesIndexRoute
  '/tsx/classroom/$classroomId/announcements': typeof ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute
  '/tsx/classroom/$classroomId/chat': typeof ProtectedTsxClassroomLayoutClassroomIdChatRoute
  '/tsx/classroom/$classroomId/lectures': typeof ProtectedTsxClassroomLayoutClassroomIdLecturesRoute
  '/tsx/classroom/$classroomId/': typeof ProtectedTsxClassroomLayoutClassroomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tsx': typeof ProtectedTsxProtectedRoute
  '/tsx/dashboard': typeof ProtectedTsxDashboardRoute
  '/tsx/notifications': typeof ProtectedTsxNotificationsRoute
  '/tsx/checkout/$course': typeof ProtectedTsxCheckoutCourseRoute
  '/tsx/classroom': typeof ProtectedTsxClassroomLayoutRouteWithChildren
  '/tsx/courses/$courseId': typeof ProtectedTsxCoursesCourseIdRoute
  '/tsx/profile/$userId': typeof ProtectedTsxProfileUserIdRoute
  '/tsx/profile/settings': typeof ProtectedTsxProfileSettingsRoute
  '/tsx/courses': typeof ProtectedTsxCoursesIndexRoute
  '/tsx/classroom/$classroomId/announcements': typeof ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute
  '/tsx/classroom/$classroomId/chat': typeof ProtectedTsxClassroomLayoutClassroomIdChatRoute
  '/tsx/classroom/$classroomId/lectures': typeof ProtectedTsxClassroomLayoutClassroomIdLecturesRoute
  '/tsx/classroom/$classroomId': typeof ProtectedTsxClassroomLayoutClassroomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/tsx/_protected': typeof ProtectedTsxProtectedRoute
  '/_protected/tsx/dashboard': typeof ProtectedTsxDashboardRoute
  '/_protected/tsx/notifications': typeof ProtectedTsxNotificationsRoute
  '/_protected/tsx/checkout/$course': typeof ProtectedTsxCheckoutCourseRoute
  '/_protected/tsx/classroom/_layout': typeof ProtectedTsxClassroomLayoutRouteWithChildren
  '/_protected/tsx/courses/$courseId': typeof ProtectedTsxCoursesCourseIdRoute
  '/_protected/tsx/profile/$userId': typeof ProtectedTsxProfileUserIdRoute
  '/_protected/tsx/profile/settings': typeof ProtectedTsxProfileSettingsRoute
  '/_protected/tsx/courses/': typeof ProtectedTsxCoursesIndexRoute
  '/_protected/tsx/classroom/_layout/$classroomId/announcements': typeof ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute
  '/_protected/tsx/classroom/_layout/$classroomId/chat': typeof ProtectedTsxClassroomLayoutClassroomIdChatRoute
  '/_protected/tsx/classroom/_layout/$classroomId/lectures': typeof ProtectedTsxClassroomLayoutClassroomIdLecturesRoute
  '/_protected/tsx/classroom/_layout/$classroomId/': typeof ProtectedTsxClassroomLayoutClassroomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/tsx'
    | '/tsx/dashboard'
    | '/tsx/notifications'
    | '/tsx/checkout/$course'
    | '/tsx/classroom'
    | '/tsx/courses/$courseId'
    | '/tsx/profile/$userId'
    | '/tsx/profile/settings'
    | '/tsx/courses/'
    | '/tsx/classroom/$classroomId/announcements'
    | '/tsx/classroom/$classroomId/chat'
    | '/tsx/classroom/$classroomId/lectures'
    | '/tsx/classroom/$classroomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/tsx'
    | '/tsx/dashboard'
    | '/tsx/notifications'
    | '/tsx/checkout/$course'
    | '/tsx/classroom'
    | '/tsx/courses/$courseId'
    | '/tsx/profile/$userId'
    | '/tsx/profile/settings'
    | '/tsx/courses'
    | '/tsx/classroom/$classroomId/announcements'
    | '/tsx/classroom/$classroomId/chat'
    | '/tsx/classroom/$classroomId/lectures'
    | '/tsx/classroom/$classroomId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_protected/tsx/_protected'
    | '/_protected/tsx/dashboard'
    | '/_protected/tsx/notifications'
    | '/_protected/tsx/checkout/$course'
    | '/_protected/tsx/classroom/_layout'
    | '/_protected/tsx/courses/$courseId'
    | '/_protected/tsx/profile/$userId'
    | '/_protected/tsx/profile/settings'
    | '/_protected/tsx/courses/'
    | '/_protected/tsx/classroom/_layout/$classroomId/announcements'
    | '/_protected/tsx/classroom/_layout/$classroomId/chat'
    | '/_protected/tsx/classroom/_layout/$classroomId/lectures'
    | '/_protected/tsx/classroom/_layout/$classroomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProtectedTsxProtectedRoute: typeof ProtectedTsxProtectedRoute
  ProtectedTsxDashboardRoute: typeof ProtectedTsxDashboardRoute
  ProtectedTsxNotificationsRoute: typeof ProtectedTsxNotificationsRoute
  ProtectedTsxCheckoutCourseRoute: typeof ProtectedTsxCheckoutCourseRoute
  ProtectedTsxClassroomLayoutRoute: typeof ProtectedTsxClassroomLayoutRouteWithChildren
  ProtectedTsxCoursesCourseIdRoute: typeof ProtectedTsxCoursesCourseIdRoute
  ProtectedTsxProfileUserIdRoute: typeof ProtectedTsxProfileUserIdRoute
  ProtectedTsxProfileSettingsRoute: typeof ProtectedTsxProfileSettingsRoute
  ProtectedTsxCoursesIndexRoute: typeof ProtectedTsxCoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/notifications': {
      id: '/_protected/tsx/notifications'
      path: '/tsx/notifications'
      fullPath: '/tsx/notifications'
      preLoaderRoute: typeof ProtectedTsxNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/dashboard': {
      id: '/_protected/tsx/dashboard'
      path: '/tsx/dashboard'
      fullPath: '/tsx/dashboard'
      preLoaderRoute: typeof ProtectedTsxDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/_protected': {
      id: '/_protected/tsx/_protected'
      path: '/tsx'
      fullPath: '/tsx'
      preLoaderRoute: typeof ProtectedTsxProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/courses/': {
      id: '/_protected/tsx/courses/'
      path: '/tsx/courses'
      fullPath: '/tsx/courses/'
      preLoaderRoute: typeof ProtectedTsxCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/profile/settings': {
      id: '/_protected/tsx/profile/settings'
      path: '/tsx/profile/settings'
      fullPath: '/tsx/profile/settings'
      preLoaderRoute: typeof ProtectedTsxProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/profile/$userId': {
      id: '/_protected/tsx/profile/$userId'
      path: '/tsx/profile/$userId'
      fullPath: '/tsx/profile/$userId'
      preLoaderRoute: typeof ProtectedTsxProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/courses/$courseId': {
      id: '/_protected/tsx/courses/$courseId'
      path: '/tsx/courses/$courseId'
      fullPath: '/tsx/courses/$courseId'
      preLoaderRoute: typeof ProtectedTsxCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/classroom/_layout': {
      id: '/_protected/tsx/classroom/_layout'
      path: '/tsx/classroom'
      fullPath: '/tsx/classroom'
      preLoaderRoute: typeof ProtectedTsxClassroomLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/checkout/$course': {
      id: '/_protected/tsx/checkout/$course'
      path: '/tsx/checkout/$course'
      fullPath: '/tsx/checkout/$course'
      preLoaderRoute: typeof ProtectedTsxCheckoutCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tsx/classroom/_layout/$classroomId/': {
      id: '/_protected/tsx/classroom/_layout/$classroomId/'
      path: '/$classroomId'
      fullPath: '/tsx/classroom/$classroomId/'
      preLoaderRoute: typeof ProtectedTsxClassroomLayoutClassroomIdIndexRouteImport
      parentRoute: typeof ProtectedTsxClassroomLayoutRoute
    }
    '/_protected/tsx/classroom/_layout/$classroomId/lectures': {
      id: '/_protected/tsx/classroom/_layout/$classroomId/lectures'
      path: '/$classroomId/lectures'
      fullPath: '/tsx/classroom/$classroomId/lectures'
      preLoaderRoute: typeof ProtectedTsxClassroomLayoutClassroomIdLecturesRouteImport
      parentRoute: typeof ProtectedTsxClassroomLayoutRoute
    }
    '/_protected/tsx/classroom/_layout/$classroomId/chat': {
      id: '/_protected/tsx/classroom/_layout/$classroomId/chat'
      path: '/$classroomId/chat'
      fullPath: '/tsx/classroom/$classroomId/chat'
      preLoaderRoute: typeof ProtectedTsxClassroomLayoutClassroomIdChatRouteImport
      parentRoute: typeof ProtectedTsxClassroomLayoutRoute
    }
    '/_protected/tsx/classroom/_layout/$classroomId/announcements': {
      id: '/_protected/tsx/classroom/_layout/$classroomId/announcements'
      path: '/$classroomId/announcements'
      fullPath: '/tsx/classroom/$classroomId/announcements'
      preLoaderRoute: typeof ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRouteImport
      parentRoute: typeof ProtectedTsxClassroomLayoutRoute
    }
  }
}

interface ProtectedTsxClassroomLayoutRouteChildren {
  ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute: typeof ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute
  ProtectedTsxClassroomLayoutClassroomIdChatRoute: typeof ProtectedTsxClassroomLayoutClassroomIdChatRoute
  ProtectedTsxClassroomLayoutClassroomIdLecturesRoute: typeof ProtectedTsxClassroomLayoutClassroomIdLecturesRoute
  ProtectedTsxClassroomLayoutClassroomIdIndexRoute: typeof ProtectedTsxClassroomLayoutClassroomIdIndexRoute
}

const ProtectedTsxClassroomLayoutRouteChildren: ProtectedTsxClassroomLayoutRouteChildren =
  {
    ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute:
      ProtectedTsxClassroomLayoutClassroomIdAnnouncementsRoute,
    ProtectedTsxClassroomLayoutClassroomIdChatRoute:
      ProtectedTsxClassroomLayoutClassroomIdChatRoute,
    ProtectedTsxClassroomLayoutClassroomIdLecturesRoute:
      ProtectedTsxClassroomLayoutClassroomIdLecturesRoute,
    ProtectedTsxClassroomLayoutClassroomIdIndexRoute:
      ProtectedTsxClassroomLayoutClassroomIdIndexRoute,
  }

const ProtectedTsxClassroomLayoutRouteWithChildren =
  ProtectedTsxClassroomLayoutRoute._addFileChildren(
    ProtectedTsxClassroomLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProtectedTsxProtectedRoute: ProtectedTsxProtectedRoute,
  ProtectedTsxDashboardRoute: ProtectedTsxDashboardRoute,
  ProtectedTsxNotificationsRoute: ProtectedTsxNotificationsRoute,
  ProtectedTsxCheckoutCourseRoute: ProtectedTsxCheckoutCourseRoute,
  ProtectedTsxClassroomLayoutRoute:
    ProtectedTsxClassroomLayoutRouteWithChildren,
  ProtectedTsxCoursesCourseIdRoute: ProtectedTsxCoursesCourseIdRoute,
  ProtectedTsxProfileUserIdRoute: ProtectedTsxProfileUserIdRoute,
  ProtectedTsxProfileSettingsRoute: ProtectedTsxProfileSettingsRoute,
  ProtectedTsxCoursesIndexRoute: ProtectedTsxCoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
