/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedNotificationsIndexRouteImport } from './routes/_protected/notifications/index'
import { Route as ProtectedMyCoursesIndexRouteImport } from './routes/_protected/my-courses/index'
import { Route as ProtectedCoursesIndexRouteImport } from './routes/_protected/courses/index'
import { Route as ProtectedProfileSettingsRouteImport } from './routes/_protected/profile/settings'
import { Route as ProtectedProfileUserIdRouteImport } from './routes/_protected/profile/$userId'
import { Route as ProtectedPaymentsHistoryRouteImport } from './routes/_protected/payments/history'
import { Route as ProtectedCoursesCourseIdRouteImport } from './routes/_protected/courses/$courseId'
import { Route as ProtectedClassroomLayoutRouteImport } from './routes/_protected/classroom/_layout'
import { Route as ProtectedCheckoutCourseIdRouteImport } from './routes/_protected/checkout/$courseId'
import { Route as ProtectedTeacherCoursesIndexRouteImport } from './routes/_protected/teacher/courses/index'
import { Route as ProtectedClassroomClassroomIdIndexRouteImport } from './routes/_protected/classroom/$classroomId/index'
import { Route as ProtectedTeacherCoursesCreateRouteImport } from './routes/_protected/teacher/courses/create'
import { Route as ProtectedClassroomClassroomIdQuizzesIndexRouteImport } from './routes/_protected/classroom/$classroomId/quizzes/index'
import { Route as ProtectedClassroomClassroomIdLecturesIndexRouteImport } from './routes/_protected/classroom/$classroomId/lectures/index'
import { Route as ProtectedClassroomClassroomIdEnrollmentsIndexRouteImport } from './routes/_protected/classroom/$classroomId/enrollments/index'
import { Route as ProtectedClassroomClassroomIdChatIndexRouteImport } from './routes/_protected/classroom/$classroomId/chat/index'
import { Route as ProtectedClassroomClassroomIdAssignmentsIndexRouteImport } from './routes/_protected/classroom/$classroomId/assignments/index'
import { Route as ProtectedClassroomClassroomIdAnnouncementsIndexRouteImport } from './routes/_protected/classroom/$classroomId/announcements/index'
import { Route as ProtectedTeacherCoursesCourseIdStudentsRouteImport } from './routes/_protected/teacher/courses/$courseId/students'
import { Route as ProtectedTeacherCoursesCourseIdEditRouteImport } from './routes/_protected/teacher/courses/$courseId/edit'
import { Route as ProtectedClassroomClassroomIdLecturesLectureIdRouteImport } from './routes/_protected/classroom/$classroomId/lectures/$lectureId'
import { Route as ProtectedClassroomClassroomIdQuizzesQuizIdEditRouteImport } from './routes/_protected/classroom/$classroomId/quizzes/$quizId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedNotificationsIndexRoute =
  ProtectedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMyCoursesIndexRoute = ProtectedMyCoursesIndexRouteImport.update({
  id: '/my-courses/',
  path: '/my-courses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesIndexRoute = ProtectedCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileSettingsRoute =
  ProtectedProfileSettingsRouteImport.update({
    id: '/profile/settings',
    path: '/profile/settings',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProfileUserIdRoute = ProtectedProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPaymentsHistoryRoute =
  ProtectedPaymentsHistoryRouteImport.update({
    id: '/payments/history',
    path: '/payments/history',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCoursesCourseIdRoute =
  ProtectedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomLayoutRoute =
  ProtectedClassroomLayoutRouteImport.update({
    id: '/classroom/_layout',
    path: '/classroom',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCheckoutCourseIdRoute =
  ProtectedCheckoutCourseIdRouteImport.update({
    id: '/checkout/$courseId',
    path: '/checkout/$courseId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTeacherCoursesIndexRoute =
  ProtectedTeacherCoursesIndexRouteImport.update({
    id: '/teacher/courses/',
    path: '/teacher/courses/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdIndexRoute =
  ProtectedClassroomClassroomIdIndexRouteImport.update({
    id: '/classroom/$classroomId/',
    path: '/classroom/$classroomId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTeacherCoursesCreateRoute =
  ProtectedTeacherCoursesCreateRouteImport.update({
    id: '/teacher/courses/create',
    path: '/teacher/courses/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdQuizzesIndexRoute =
  ProtectedClassroomClassroomIdQuizzesIndexRouteImport.update({
    id: '/classroom/$classroomId/quizzes/',
    path: '/classroom/$classroomId/quizzes/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdLecturesIndexRoute =
  ProtectedClassroomClassroomIdLecturesIndexRouteImport.update({
    id: '/classroom/$classroomId/lectures/',
    path: '/classroom/$classroomId/lectures/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdEnrollmentsIndexRoute =
  ProtectedClassroomClassroomIdEnrollmentsIndexRouteImport.update({
    id: '/classroom/$classroomId/enrollments/',
    path: '/classroom/$classroomId/enrollments/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdChatIndexRoute =
  ProtectedClassroomClassroomIdChatIndexRouteImport.update({
    id: '/classroom/$classroomId/chat/',
    path: '/classroom/$classroomId/chat/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdAssignmentsIndexRoute =
  ProtectedClassroomClassroomIdAssignmentsIndexRouteImport.update({
    id: '/classroom/$classroomId/assignments/',
    path: '/classroom/$classroomId/assignments/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdAnnouncementsIndexRoute =
  ProtectedClassroomClassroomIdAnnouncementsIndexRouteImport.update({
    id: '/classroom/$classroomId/announcements/',
    path: '/classroom/$classroomId/announcements/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTeacherCoursesCourseIdStudentsRoute =
  ProtectedTeacherCoursesCourseIdStudentsRouteImport.update({
    id: '/teacher/courses/$courseId/students',
    path: '/teacher/courses/$courseId/students',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTeacherCoursesCourseIdEditRoute =
  ProtectedTeacherCoursesCourseIdEditRouteImport.update({
    id: '/teacher/courses/$courseId/edit',
    path: '/teacher/courses/$courseId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdLecturesLectureIdRoute =
  ProtectedClassroomClassroomIdLecturesLectureIdRouteImport.update({
    id: '/classroom/$classroomId/lectures/$lectureId',
    path: '/classroom/$classroomId/lectures/$lectureId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute =
  ProtectedClassroomClassroomIdQuizzesQuizIdEditRouteImport.update({
    id: '/classroom/$classroomId/quizzes/$quizId/edit',
    path: '/classroom/$classroomId/quizzes/$quizId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout/$courseId': typeof ProtectedCheckoutCourseIdRoute
  '/classroom': typeof ProtectedClassroomLayoutRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdRoute
  '/payments/history': typeof ProtectedPaymentsHistoryRoute
  '/profile/$userId': typeof ProtectedProfileUserIdRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/courses/': typeof ProtectedCoursesIndexRoute
  '/my-courses/': typeof ProtectedMyCoursesIndexRoute
  '/notifications/': typeof ProtectedNotificationsIndexRoute
  '/teacher/courses/create': typeof ProtectedTeacherCoursesCreateRoute
  '/classroom/$classroomId/': typeof ProtectedClassroomClassroomIdIndexRoute
  '/teacher/courses/': typeof ProtectedTeacherCoursesIndexRoute
  '/classroom/$classroomId/lectures/$lectureId': typeof ProtectedClassroomClassroomIdLecturesLectureIdRoute
  '/teacher/courses/$courseId/edit': typeof ProtectedTeacherCoursesCourseIdEditRoute
  '/teacher/courses/$courseId/students': typeof ProtectedTeacherCoursesCourseIdStudentsRoute
  '/classroom/$classroomId/announcements/': typeof ProtectedClassroomClassroomIdAnnouncementsIndexRoute
  '/classroom/$classroomId/assignments/': typeof ProtectedClassroomClassroomIdAssignmentsIndexRoute
  '/classroom/$classroomId/chat/': typeof ProtectedClassroomClassroomIdChatIndexRoute
  '/classroom/$classroomId/enrollments/': typeof ProtectedClassroomClassroomIdEnrollmentsIndexRoute
  '/classroom/$classroomId/lectures/': typeof ProtectedClassroomClassroomIdLecturesIndexRoute
  '/classroom/$classroomId/quizzes/': typeof ProtectedClassroomClassroomIdQuizzesIndexRoute
  '/classroom/$classroomId/quizzes/$quizId/edit': typeof ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout/$courseId': typeof ProtectedCheckoutCourseIdRoute
  '/classroom': typeof ProtectedClassroomLayoutRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdRoute
  '/payments/history': typeof ProtectedPaymentsHistoryRoute
  '/profile/$userId': typeof ProtectedProfileUserIdRoute
  '/profile/settings': typeof ProtectedProfileSettingsRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/my-courses': typeof ProtectedMyCoursesIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/teacher/courses/create': typeof ProtectedTeacherCoursesCreateRoute
  '/classroom/$classroomId': typeof ProtectedClassroomClassroomIdIndexRoute
  '/teacher/courses': typeof ProtectedTeacherCoursesIndexRoute
  '/classroom/$classroomId/lectures/$lectureId': typeof ProtectedClassroomClassroomIdLecturesLectureIdRoute
  '/teacher/courses/$courseId/edit': typeof ProtectedTeacherCoursesCourseIdEditRoute
  '/teacher/courses/$courseId/students': typeof ProtectedTeacherCoursesCourseIdStudentsRoute
  '/classroom/$classroomId/announcements': typeof ProtectedClassroomClassroomIdAnnouncementsIndexRoute
  '/classroom/$classroomId/assignments': typeof ProtectedClassroomClassroomIdAssignmentsIndexRoute
  '/classroom/$classroomId/chat': typeof ProtectedClassroomClassroomIdChatIndexRoute
  '/classroom/$classroomId/enrollments': typeof ProtectedClassroomClassroomIdEnrollmentsIndexRoute
  '/classroom/$classroomId/lectures': typeof ProtectedClassroomClassroomIdLecturesIndexRoute
  '/classroom/$classroomId/quizzes': typeof ProtectedClassroomClassroomIdQuizzesIndexRoute
  '/classroom/$classroomId/quizzes/$quizId/edit': typeof ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/checkout/$courseId': typeof ProtectedCheckoutCourseIdRoute
  '/_protected/classroom/_layout': typeof ProtectedClassroomLayoutRoute
  '/_protected/courses/$courseId': typeof ProtectedCoursesCourseIdRoute
  '/_protected/payments/history': typeof ProtectedPaymentsHistoryRoute
  '/_protected/profile/$userId': typeof ProtectedProfileUserIdRoute
  '/_protected/profile/settings': typeof ProtectedProfileSettingsRoute
  '/_protected/courses/': typeof ProtectedCoursesIndexRoute
  '/_protected/my-courses/': typeof ProtectedMyCoursesIndexRoute
  '/_protected/notifications/': typeof ProtectedNotificationsIndexRoute
  '/_protected/teacher/courses/create': typeof ProtectedTeacherCoursesCreateRoute
  '/_protected/classroom/$classroomId/': typeof ProtectedClassroomClassroomIdIndexRoute
  '/_protected/teacher/courses/': typeof ProtectedTeacherCoursesIndexRoute
  '/_protected/classroom/$classroomId/lectures/$lectureId': typeof ProtectedClassroomClassroomIdLecturesLectureIdRoute
  '/_protected/teacher/courses/$courseId/edit': typeof ProtectedTeacherCoursesCourseIdEditRoute
  '/_protected/teacher/courses/$courseId/students': typeof ProtectedTeacherCoursesCourseIdStudentsRoute
  '/_protected/classroom/$classroomId/announcements/': typeof ProtectedClassroomClassroomIdAnnouncementsIndexRoute
  '/_protected/classroom/$classroomId/assignments/': typeof ProtectedClassroomClassroomIdAssignmentsIndexRoute
  '/_protected/classroom/$classroomId/chat/': typeof ProtectedClassroomClassroomIdChatIndexRoute
  '/_protected/classroom/$classroomId/enrollments/': typeof ProtectedClassroomClassroomIdEnrollmentsIndexRoute
  '/_protected/classroom/$classroomId/lectures/': typeof ProtectedClassroomClassroomIdLecturesIndexRoute
  '/_protected/classroom/$classroomId/quizzes/': typeof ProtectedClassroomClassroomIdQuizzesIndexRoute
  '/_protected/classroom/$classroomId/quizzes/$quizId/edit': typeof ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/checkout/$courseId'
    | '/classroom'
    | '/courses/$courseId'
    | '/payments/history'
    | '/profile/$userId'
    | '/profile/settings'
    | '/courses/'
    | '/my-courses/'
    | '/notifications/'
    | '/teacher/courses/create'
    | '/classroom/$classroomId/'
    | '/teacher/courses/'
    | '/classroom/$classroomId/lectures/$lectureId'
    | '/teacher/courses/$courseId/edit'
    | '/teacher/courses/$courseId/students'
    | '/classroom/$classroomId/announcements/'
    | '/classroom/$classroomId/assignments/'
    | '/classroom/$classroomId/chat/'
    | '/classroom/$classroomId/enrollments/'
    | '/classroom/$classroomId/lectures/'
    | '/classroom/$classroomId/quizzes/'
    | '/classroom/$classroomId/quizzes/$quizId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/checkout/$courseId'
    | '/classroom'
    | '/courses/$courseId'
    | '/payments/history'
    | '/profile/$userId'
    | '/profile/settings'
    | '/courses'
    | '/my-courses'
    | '/notifications'
    | '/teacher/courses/create'
    | '/classroom/$classroomId'
    | '/teacher/courses'
    | '/classroom/$classroomId/lectures/$lectureId'
    | '/teacher/courses/$courseId/edit'
    | '/teacher/courses/$courseId/students'
    | '/classroom/$classroomId/announcements'
    | '/classroom/$classroomId/assignments'
    | '/classroom/$classroomId/chat'
    | '/classroom/$classroomId/enrollments'
    | '/classroom/$classroomId/lectures'
    | '/classroom/$classroomId/quizzes'
    | '/classroom/$classroomId/quizzes/$quizId/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/_protected/checkout/$courseId'
    | '/_protected/classroom/_layout'
    | '/_protected/courses/$courseId'
    | '/_protected/payments/history'
    | '/_protected/profile/$userId'
    | '/_protected/profile/settings'
    | '/_protected/courses/'
    | '/_protected/my-courses/'
    | '/_protected/notifications/'
    | '/_protected/teacher/courses/create'
    | '/_protected/classroom/$classroomId/'
    | '/_protected/teacher/courses/'
    | '/_protected/classroom/$classroomId/lectures/$lectureId'
    | '/_protected/teacher/courses/$courseId/edit'
    | '/_protected/teacher/courses/$courseId/students'
    | '/_protected/classroom/$classroomId/announcements/'
    | '/_protected/classroom/$classroomId/assignments/'
    | '/_protected/classroom/$classroomId/chat/'
    | '/_protected/classroom/$classroomId/enrollments/'
    | '/_protected/classroom/$classroomId/lectures/'
    | '/_protected/classroom/$classroomId/quizzes/'
    | '/_protected/classroom/$classroomId/quizzes/$quizId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/notifications/': {
      id: '/_protected/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof ProtectedNotificationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-courses/': {
      id: '/_protected/my-courses/'
      path: '/my-courses'
      fullPath: '/my-courses/'
      preLoaderRoute: typeof ProtectedMyCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/': {
      id: '/_protected/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof ProtectedCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/settings': {
      id: '/_protected/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProtectedProfileSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/$userId': {
      id: '/_protected/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProtectedProfileUserIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/payments/history': {
      id: '/_protected/payments/history'
      path: '/payments/history'
      fullPath: '/payments/history'
      preLoaderRoute: typeof ProtectedPaymentsHistoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$courseId': {
      id: '/_protected/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ProtectedCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/_layout': {
      id: '/_protected/classroom/_layout'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ProtectedClassroomLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/checkout/$courseId': {
      id: '/_protected/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/checkout/$courseId'
      preLoaderRoute: typeof ProtectedCheckoutCourseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teacher/courses/': {
      id: '/_protected/teacher/courses/'
      path: '/teacher/courses'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof ProtectedTeacherCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/': {
      id: '/_protected/classroom/$classroomId/'
      path: '/classroom/$classroomId'
      fullPath: '/classroom/$classroomId/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teacher/courses/create': {
      id: '/_protected/teacher/courses/create'
      path: '/teacher/courses/create'
      fullPath: '/teacher/courses/create'
      preLoaderRoute: typeof ProtectedTeacherCoursesCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/quizzes/': {
      id: '/_protected/classroom/$classroomId/quizzes/'
      path: '/classroom/$classroomId/quizzes'
      fullPath: '/classroom/$classroomId/quizzes/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdQuizzesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/lectures/': {
      id: '/_protected/classroom/$classroomId/lectures/'
      path: '/classroom/$classroomId/lectures'
      fullPath: '/classroom/$classroomId/lectures/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdLecturesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/enrollments/': {
      id: '/_protected/classroom/$classroomId/enrollments/'
      path: '/classroom/$classroomId/enrollments'
      fullPath: '/classroom/$classroomId/enrollments/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdEnrollmentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/chat/': {
      id: '/_protected/classroom/$classroomId/chat/'
      path: '/classroom/$classroomId/chat'
      fullPath: '/classroom/$classroomId/chat/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdChatIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/assignments/': {
      id: '/_protected/classroom/$classroomId/assignments/'
      path: '/classroom/$classroomId/assignments'
      fullPath: '/classroom/$classroomId/assignments/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdAssignmentsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/announcements/': {
      id: '/_protected/classroom/$classroomId/announcements/'
      path: '/classroom/$classroomId/announcements'
      fullPath: '/classroom/$classroomId/announcements/'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdAnnouncementsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teacher/courses/$courseId/students': {
      id: '/_protected/teacher/courses/$courseId/students'
      path: '/teacher/courses/$courseId/students'
      fullPath: '/teacher/courses/$courseId/students'
      preLoaderRoute: typeof ProtectedTeacherCoursesCourseIdStudentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/teacher/courses/$courseId/edit': {
      id: '/_protected/teacher/courses/$courseId/edit'
      path: '/teacher/courses/$courseId/edit'
      fullPath: '/teacher/courses/$courseId/edit'
      preLoaderRoute: typeof ProtectedTeacherCoursesCourseIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/lectures/$lectureId': {
      id: '/_protected/classroom/$classroomId/lectures/$lectureId'
      path: '/classroom/$classroomId/lectures/$lectureId'
      fullPath: '/classroom/$classroomId/lectures/$lectureId'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdLecturesLectureIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classroom/$classroomId/quizzes/$quizId/edit': {
      id: '/_protected/classroom/$classroomId/quizzes/$quizId/edit'
      path: '/classroom/$classroomId/quizzes/$quizId/edit'
      fullPath: '/classroom/$classroomId/quizzes/$quizId/edit'
      preLoaderRoute: typeof ProtectedClassroomClassroomIdQuizzesQuizIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedCheckoutCourseIdRoute: typeof ProtectedCheckoutCourseIdRoute
  ProtectedClassroomLayoutRoute: typeof ProtectedClassroomLayoutRoute
  ProtectedCoursesCourseIdRoute: typeof ProtectedCoursesCourseIdRoute
  ProtectedPaymentsHistoryRoute: typeof ProtectedPaymentsHistoryRoute
  ProtectedProfileUserIdRoute: typeof ProtectedProfileUserIdRoute
  ProtectedProfileSettingsRoute: typeof ProtectedProfileSettingsRoute
  ProtectedCoursesIndexRoute: typeof ProtectedCoursesIndexRoute
  ProtectedMyCoursesIndexRoute: typeof ProtectedMyCoursesIndexRoute
  ProtectedNotificationsIndexRoute: typeof ProtectedNotificationsIndexRoute
  ProtectedTeacherCoursesCreateRoute: typeof ProtectedTeacherCoursesCreateRoute
  ProtectedClassroomClassroomIdIndexRoute: typeof ProtectedClassroomClassroomIdIndexRoute
  ProtectedTeacherCoursesIndexRoute: typeof ProtectedTeacherCoursesIndexRoute
  ProtectedClassroomClassroomIdLecturesLectureIdRoute: typeof ProtectedClassroomClassroomIdLecturesLectureIdRoute
  ProtectedTeacherCoursesCourseIdEditRoute: typeof ProtectedTeacherCoursesCourseIdEditRoute
  ProtectedTeacherCoursesCourseIdStudentsRoute: typeof ProtectedTeacherCoursesCourseIdStudentsRoute
  ProtectedClassroomClassroomIdAnnouncementsIndexRoute: typeof ProtectedClassroomClassroomIdAnnouncementsIndexRoute
  ProtectedClassroomClassroomIdAssignmentsIndexRoute: typeof ProtectedClassroomClassroomIdAssignmentsIndexRoute
  ProtectedClassroomClassroomIdChatIndexRoute: typeof ProtectedClassroomClassroomIdChatIndexRoute
  ProtectedClassroomClassroomIdEnrollmentsIndexRoute: typeof ProtectedClassroomClassroomIdEnrollmentsIndexRoute
  ProtectedClassroomClassroomIdLecturesIndexRoute: typeof ProtectedClassroomClassroomIdLecturesIndexRoute
  ProtectedClassroomClassroomIdQuizzesIndexRoute: typeof ProtectedClassroomClassroomIdQuizzesIndexRoute
  ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute: typeof ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCheckoutCourseIdRoute: ProtectedCheckoutCourseIdRoute,
  ProtectedClassroomLayoutRoute: ProtectedClassroomLayoutRoute,
  ProtectedCoursesCourseIdRoute: ProtectedCoursesCourseIdRoute,
  ProtectedPaymentsHistoryRoute: ProtectedPaymentsHistoryRoute,
  ProtectedProfileUserIdRoute: ProtectedProfileUserIdRoute,
  ProtectedProfileSettingsRoute: ProtectedProfileSettingsRoute,
  ProtectedCoursesIndexRoute: ProtectedCoursesIndexRoute,
  ProtectedMyCoursesIndexRoute: ProtectedMyCoursesIndexRoute,
  ProtectedNotificationsIndexRoute: ProtectedNotificationsIndexRoute,
  ProtectedTeacherCoursesCreateRoute: ProtectedTeacherCoursesCreateRoute,
  ProtectedClassroomClassroomIdIndexRoute:
    ProtectedClassroomClassroomIdIndexRoute,
  ProtectedTeacherCoursesIndexRoute: ProtectedTeacherCoursesIndexRoute,
  ProtectedClassroomClassroomIdLecturesLectureIdRoute:
    ProtectedClassroomClassroomIdLecturesLectureIdRoute,
  ProtectedTeacherCoursesCourseIdEditRoute:
    ProtectedTeacherCoursesCourseIdEditRoute,
  ProtectedTeacherCoursesCourseIdStudentsRoute:
    ProtectedTeacherCoursesCourseIdStudentsRoute,
  ProtectedClassroomClassroomIdAnnouncementsIndexRoute:
    ProtectedClassroomClassroomIdAnnouncementsIndexRoute,
  ProtectedClassroomClassroomIdAssignmentsIndexRoute:
    ProtectedClassroomClassroomIdAssignmentsIndexRoute,
  ProtectedClassroomClassroomIdChatIndexRoute:
    ProtectedClassroomClassroomIdChatIndexRoute,
  ProtectedClassroomClassroomIdEnrollmentsIndexRoute:
    ProtectedClassroomClassroomIdEnrollmentsIndexRoute,
  ProtectedClassroomClassroomIdLecturesIndexRoute:
    ProtectedClassroomClassroomIdLecturesIndexRoute,
  ProtectedClassroomClassroomIdQuizzesIndexRoute:
    ProtectedClassroomClassroomIdQuizzesIndexRoute,
  ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute:
    ProtectedClassroomClassroomIdQuizzesQuizIdEditRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
